### ISSUE TITLE
Renew this project

### ISSUE THREAD

**Issue by turtton** [YukkuriLaboratory/FabSit#1]
Original repository looks abandoned, so I am planing to renew this project.

### Processes
- Add gametests to reproduce bugs I found and ci checks
- Rewrite codes and fix bugs
- Renew brandings

### Bugs
- Key shortcuts does not work in singlepalyers
- Players slipped down or cannot pose on bottom slab block

**Comment by williamistGitHub** [comment]
tyvm for this, wanted to use the mod on my 1.20.1 server :)

**Comment by turtton** [comment]
> tyvm for this, wanted to use the mod on my 1.20.1 server :)

Can you build this mod yourself? This repository has 1.20.1 branch and it works(but it has some bugs).

I am planning to support 1.20.2 or above for now, so if you still want to support 1.20.1 after this project renewed it, please tell me again.

**Comment by williamistGitHub** [comment]
I built it myself, but it crashed the server (but not the client) when we added it. I've asked my friend that runs the server for the crash log and I'm gonna try to fix the crash, but he wont be awake until tomorrow. If you'd like I could also PR the fix here if I can get it to work.

**Comment by turtton** [comment]
ok...It looks I overlooked a mistake. If you could fix it, I world be happy that you to open PR, but if not, please share logs.
